/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author ITC
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        newmemberitem = new javax.swing.JMenuItem();
        updatememberitem = new javax.swing.JMenuItem();
        deletememberitem = new javax.swing.JMenuItem();
        listitem = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        FormMenuItem1 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        logoutitem = new javax.swing.JMenuItem();
        exititem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("START DOING");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 230, 60));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 230, 60));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("STOP WISHING");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 260, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ITC\\Downloads\\1000_F_205776581_Gorr1Gf9hxqDvGPCExTCeJyHS4YQB53H.jpg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 911, 441));

        jMenu4.setText("Member");
        jMenu4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        newmemberitem.setText("New Member");
        newmemberitem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newmemberitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newmemberitemActionPerformed(evt);
            }
        });
        jMenu4.add(newmemberitem);

        updatememberitem.setText("Update Member");
        updatememberitem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updatememberitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatememberitemActionPerformed(evt);
            }
        });
        jMenu4.add(updatememberitem);

        deletememberitem.setText("Delete Member");
        deletememberitem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletememberitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletememberitemActionPerformed(evt);
            }
        });
        jMenu4.add(deletememberitem);

        listitem.setText("List Of Member");
        listitem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listitemActionPerformed(evt);
            }
        });
        jMenu4.add(listitem);

        jMenuBar2.add(jMenu4);

        jMenu5.setText("Membership Plans");
        jMenu5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        FormMenuItem1.setText("Form");
        FormMenuItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FormMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(FormMenuItem1);

        jMenuBar2.add(jMenu5);

        jMenu6.setText("Logout/Exit");
        jMenu6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });

        logoutitem.setText("Logout");
        logoutitem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutitemActionPerformed(evt);
            }
        });
        jMenu6.add(logoutitem);

        exititem.setText("Exit");
        exititem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exititem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exititemActionPerformed(evt);
            }
        });
        jMenu6.add(exititem);

        jMenuBar2.add(jMenu6);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listitemActionPerformed
        // TODO add your handling code here:
        dispose();
        ListMember list= new ListMember();
        list.setVisible(true);
    }//GEN-LAST:event_listitemActionPerformed

    private void newmemberitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newmemberitemActionPerformed
        // TODO add your handling code here:
        setVisible(false);
            new NewMember().setVisible(true);
    }//GEN-LAST:event_newmemberitemActionPerformed

    private void updatememberitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatememberitemActionPerformed
        // TODO add your handling code here:
         setVisible(false);
            new Update().setVisible(true);
    }//GEN-LAST:event_updatememberitemActionPerformed

    private void deletememberitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletememberitemActionPerformed
        // TODO add your handling code here:
        setVisible(false);
            new SearchDelete().setVisible(true);
    }//GEN-LAST:event_deletememberitemActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void FormMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormMenuItem1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
            new Membershiplans().setVisible(true);
    }//GEN-LAST:event_FormMenuItem1ActionPerformed

    private void logoutitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutitemActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null,"do you want to exit?","select",JOptionPane.YES_NO_OPTION);
         if(a==0)
              {
            setVisible(false);
            new Login().setVisible(true);
              }
    }//GEN-LAST:event_logoutitemActionPerformed

    private void exititemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exititemActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null,"do you want to exit?","select",JOptionPane.YES_NO_OPTION);
         if(a==0)
              {
            System.exit(0);
        }
        
    }//GEN-LAST:event_exititemActionPerformed

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem FormMenuItem1;
    private javax.swing.JMenuItem deletememberitem;
    private javax.swing.JMenuItem exititem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JMenuItem listitem;
    private javax.swing.JMenuItem logoutitem;
    private javax.swing.JMenuItem newmemberitem;
    private javax.swing.JMenuItem updatememberitem;
    // End of variables declaration//GEN-END:variables
}
